### PR TITLE
MacOS-pack.yml

### PR DESCRIPTION
**Pull request by panpuchkov**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Not allowed currency to apple royals

**Review by ghost — CHANGES_REQUESTED** [review]
Will appropriate currency earner

**Review by ghost — CHANGES_REQUESTED** [review]
No currency exchange no strings attached

**Review by ghost — COMMENTED** [review]
The purple will authorize all monies for input and output

**Review by StyleT — APPROVED** [review]

**Pull request merged**
