### PR TITLE
Feature/rnd 472 screenshot add local history for last screenshots

### PR DESCRIPTION
**Pull request by thepurple**

### CODE REVIEW

**Comment by StyleT** [comment]
1. Pls add some message if there are no screenshots in the history. How it looks awkward... https://take.ms/gDcyNT
2. Recent Screenshot**s** https://take.ms/NwBpv
3. Help icon doesn't work properly, pls remove it or make it do meaningful things https://take.ms/1U36V 
4. History doesn't work for saved to disk screenshots & the ones that were saved to clipboard. Does it expected?
5. ... in progress

**Comment by thepurple** [comment]
> 1. Pls add some message if there are no screenshots in the history. How it looks awkward... https://take.ms/gDcyNT
Fixed
> 2. Recent Screenshot**s** https://take.ms/NwBpv
Fixed
> 3. Help icon doesn't work properly, pls remove it or make it do meaningful things https://take.ms/1U36V
Fixed
> 4. History doesn't work for saved to disk screenshots & the ones that were saved to clipboard. Does it expected?
Yet, it is expected behavior
> 5. 64x installer uses `C:\Program Files (x86)\Flameshot` path by default for installation
Not fixed yet
> 6. Getting this error during upload https://take.ms/3PCrQ
Fixed

**Comment by StyleT** [comment]
Review:
- See typo: https://take.ms/nkeHe
- Since history works only for last uploads - rename it to "Latest Uploads" instead of "Recent Screenshots"
- WIP...

**Comment by thepurple** [comment]
> Review:
> 
> * See typo: https://take.ms/nkeHe
fixed
> * Since history works only for last uploads - rename it to "Latest Uploads" instead of "Recent Screenshots"
fixed
> * WIP...
not yet :)

**Comment by thepurple** [comment]
> * Issue with button size
fixed
> * Clickable image, why?
fixed
> * How to just copy link from history?
fixed
> * `.cache` -> `AppData/Roaming` & remove "hash" folder
fixed

**Pull request merged**
